# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

tuist_path = ENV["TUIST_PATH"] || "/opt/homebrew/bin/tuist"  # 기본 경로 지정


  lane :setup_and_build do
     sh("#{tuist_path} clean")
     sh("#{tuist_path} install")
     sh("#{tuist_path} generate")
     match(type: "development")
     build_app(scheme: "Bridging")
   end
end
